name: Port Review
description: Have a port already themed? Submit it for review here!
title: "Name of the application/tool/website/etc."
labels: ["port request", "ready for review"]
body:
  - type: input
    attributes:
      label: Link to repository
      description: Please link the repository of the port.
      placeholder: https://github.com/user/example.git
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: Show off some screenshots of the completed port!
  - type: textarea
    attributes:
      label: Any additional comments?
      description: Add any information that hasn't been covered in the previous sections!
  - type: checkboxes
    attributes:
      label: Checklist
      description: Make sure that agree with and have followed the checklist below!
      options:
        - label: I agree to follow Catppuccin's [Code Of Conduct](https://github.com/catppuccin/.github/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: I have followed Catppuccin's [submission guidelines](https://github.com/catppuccin/catppuccin/blob/main/docs/port-creation.md#submission)
          required: true
        - label: I have followed Catppuccin's [styling guidelines](https://github.com/catppuccin/catppuccin/blob/main/docs/port-creation.md#styling)
          required: true
