# This is a TOML document.

title = "TOML Example"
description = """
    Multiline
    description
"""
date = 2019-11-04T07:32:00-08:00

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
"connection_max" = 5000
enabled = true

[servers]
alpha = { ip = '10.0.0.1', dc = "eqdc10" }
beta = { ip = '10.0.0.2', dc = "eqdc10" }

[clients]
data = [ ["gamma", "delta"], [1.0, 2.0] ]

hosts = [
  "alpha",
  "omega",
]

valid-escapes = """\tline \"1\"
    line\u00202
    line 3\U0000002E
"""
invalid-escapes = "\a \u20 \U0020"
