/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unique identifier for the category.
 */
export type Key =
  | "3d_modelling"
  | "analytics"
  | "application_launcher"
  | "artificial_intelligence"
  | "boot_loader"
  | "browser"
  | "browser_extension"
  | "cli"
  | "code_editor"
  | "desktop_environment"
  | "development"
  | "discussion_forum"
  | "document_viewer"
  | "documentation_generator"
  | "education"
  | "email_client"
  | "entertainment"
  | "file_manager"
  | "game"
  | "game_development"
  | "health_and_fitness"
  | "library"
  | "music"
  | "news_and_journalism"
  | "note_taking"
  | "notification_daemon"
  | "package_registry"
  | "photo_and_video"
  | "productivity"
  | "search_engine"
  | "social_networking"
  | "syntax_highlighting"
  | "system"
  | "terminal"
  | "translation_tool"
  | "userstyle"
  | "wiki"
  | "window_manager";
/**
 * Display name of the category.
 */
export type Name = string;
/**
 * Detailed description of what the category is.
 */
export type Description = string;
/**
 * Emoji representing the category.
 */
export type Emoji = string;
/**
 * The categories listed in the README.
 */
export type CategoryDefinitions = CategoryItem[];

export interface CategoryItem {
  key: Key;
  name: Name;
  description: Description;
  emoji: Emoji;
}
